### ISSUE TITLE
appimage url not updated

### ISSUE THREAD

**Issue by LyzardKing** [texstudio-org/texstudio-meta#2]
Hi,
there are two links to the appimage download in the index.html page.
Both point to an older version.
Is there an automated way to update that or are the other links changed "manually"
with every new release?

**Comment by benibela** [comment]
there is a script https://github.com/texstudio-org/texstudio-meta/blob/de4dc254ea0f6280d92f783a45bce909ab73aa04/webpage/scripts/merge_table_others.sh

**Comment by LyzardKing** [comment]
thanks.
That script seems to get the latest from github (I'm not sure though...)
But I don't think I can use it to update the url on the website..

**Comment by LyzardKing** [comment]
Great! Thanks!
